version: 2.1
# Define the jobs we want to run for this project
jobs:
  build-and-test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - attach_workspace:
          at: .
      - checkout
      - node/install:
          install-yarn: true
          node-version: 10.15.2
      - run: node --version
      - run: npm install
      - run: npm test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: docs
          destination: docs
orbs:
  node: circleci/node@2.1.1
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build-and-test
