version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: 10.15.2
      - run: node --version
      - run: npm install
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: 10.15.2
      - run: node --version
      - run: npm install
      - run: npm test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
