jobs:
  install-node:
    docker:
      - image: 'cimg/base:default'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: 10.15.1
      - run: node --version
orbs:
  node: circleci/node@2.1.1
version: 2.1
workflows:
  test_my_app:
    jobs:
      - install-node
