jobs:
  install-node:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: 10.15.2
      - run: node --version
  build-and-test:
    steps:
      - run: npm install
      - run: npm test
orbs:
  node: circleci/node@2.1.1
version: 2.1
workflows:
  test_my_app:
    jobs:
      - install-node
      - build-and-test
